name: oggm_fsm
channels:
  - conda-forge
dependencies:
  - python==3.11.0
  - numpy
  - jupyter
  - jupyterlab
  - scipy
  - pandas
  - shapely
  - matplotlib
  - Pillow
  - netcdf4
  - scikit-image
  - scikit-learn
  - configobj
  - xarray
  - pytest
  - dask
  - bottleneck
  - pyproj
  - cartopy
  - geopandas
  - rasterio
  - rioxarray
  - seaborn
  - salem
  - motionless
  - f90nml
  - ipython
  - pip 
  - pip:
    - meson
    - ninja
    - tables
    - joblib
    - progressbar2
